version: 2.1
jobs:
  build-and-test-client:
    docker: 
      - image: circleci/node:12.16.1-node-browsers
    steps:
      - checkout
      - run: sudo npm install -g @angular/cli > /dev/null
      - run: cd client && npm install
      - run: cd client && ng test --configuration=ci
workflows:
    build-and-test-client:
      jobs:
        - build-and-test-client