version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12.16.1-browsers
    steps:
      - checkout
      - run: sudo npm install -g @angular/cli > /dev/null
      - run: cd client && npm install
      - run: cd client && ng test --configuration=ci
      - run: cd client && ng build --prod
      - run: cd client && zip -r client.zip www
      - store_artifacts:
          path: client/client.zip