version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    working_directory: ~/client
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: export NG_CLI_ANALYTICS=ci
            - run: sudo npm install @angular/cli -g
            - run: npm install
            - run: ng test --configuration=ci
workflows:
    build-and-test-client:
      jobs:
        - build-and-test-client