version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    executor:
      name: node/default
    working_directory: ~/client
    steps:
      - checkout
      - run:
        name: install-global-angular
        command: 'sudo npm install @angular/cli -g'
      - node/with-cache:
          steps:
            - run: npm install
            - run: ng test --configuration=ci
workflows:
    build-and-test:
      jobs:
        - build-and-test-client